import Footer from "@/components/Footer";

import Menu from "@/components/Menu";

import "./globals.css";
import localFont from "next/font/local";
import NextAuthProvider from "../providers/nextAuthProvider";
import { Provider } from "react-redux";
import store from "@/redux/store";
import Providers from "@/redux/Providers";
const vazir = localFont({
  src: [
    {
      path: "../public/fonts/Vazir-Light.woff2",
      weight: "100",
      style: "normal",
    },
    {
      path: "../public/fonts/Vazir-Medium.woff2",
      weight: "200",
      style: "normal",
    },
    {
      path: "../public/fonts/Vazir-Bold.woff2",
      weight: "400",
      style: "normal",
    },
  ],
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <head>
        <link href="/output.css" rel="stylesheet" />
      </head>
      <body className={vazir.className}>
        <Providers>
          <NextAuthProvider>
            <Menu />
            {children}
            <Footer />
          </NextAuthProvider>
        </Providers>
      </body>
    </html>
  );
}
